<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Coding_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

c = np.array([[4, 10, 8], [10, 26, 26], [8, 26, 61]])
inv_c = np.linalg.inv(c)
print(c)
print()
print(inv_c)

d = np.array([[44], [128], [214]])

x = np.dot(inv_c, d)
print()
print(x)

z = np.dot(c, x) #checking
print()
print(z)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]

[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]

[[-8.]
 [ 6.]
 [ 2.]]

[[ 44.]
 [128.]
 [214.]]
