<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Coding_Activity_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 
from numpy.linalg import eig


In [15]:
A = np.array([[-12, 3],[4, 1]]) 
print(f'Matrix A:\n {A}') 

inv_A = np.linalg.inv(A) 
print(f'\nInverse of Matrix A:\n{inv_A}')

B = np.array([[0],[0]]) 
print(f'\nMatrix B:\n {B}') 

X = np.dot(inv_A, B)
print(f'\nDot product:\n{X}') 

Matrix A:
 [[-12   3]
 [  4   1]]

Inverse of Matrix A:
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

Matrix B:
 [[0]
 [0]]

Dot product:
[[0.]
 [0.]]


In [16]:
A = np.array([[-6,3],[4,5]])
print(f'Matrix A:\n{A}')

w,v = np.linalg.eig(A)
print(f'the eigenvalue/s is/are:\n {w}')
print(f'the right eigenvectors are:\n {v}')


Matrix A:
[[-6  3]
 [ 4  5]]
the eigenvalue/s is/are:
 [-7.  6.]
the right eigenvectors are:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [19]:
A = np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)
s,t = np.linalg.eig(A) 
print(f'\nthe Eigenvalue/s is/are: {s.round()}')
print(f'\nthe right Eigenvectors are: \n{t.round()}\n')
c = np.dot(A,t.round())
print(c) 

[[2 2 4]
 [1 3 5]
 [2 3 4]]

the Eigenvalue/s is/are: [ 9.  1. -1.]

the right Eigenvectors are: 
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
