<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a Python code to show as its solution. Save it as "Determinant of Matrix" in your GitHub repository.

In [3]:
import numpy as np
A = np.array([[1,2,-1],[4,6,-2],[-1,3,3]])
print(A)
B = round(np.linalg.det(A))
print(B)


[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-14
