<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1


In [34]:
import numpy as np 
A = np.array([[1, 1, 1],[1, 0, 4],[0, 0, 5]])
print(f'Matrix A:\n {A}') 
print()
B = np.array([[89],[89],[95]])
print(f'Matrix B:\n {A}') 
C = np.linalg.inv(A).dot(B)
print(f'\nInverse of Matrix A:\n{C}')


Matrix A:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B:
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Inverse of Matrix A:
[[13.]
 [57.]
 [19.]]


#2


In [47]:
import numpy as np 
A = np.array([[3, -1, 1],[9, 3, -3],[-12, 4, -4]]) 
print(f'Matrix A:\n {A}') 

#as we all know a singular matrix is one with a determinant of zero and thus no inverse. since the given matrix is singular, it has no inverse so we cannot solve it properly. 
#to show it's output we can use an alt which is the pseudoinverse(pinv). 

pinv_A = np.linalg.pinv(A) 
print(f'\nPINV:\n{inv_A}')
print()

B = np.array([[5],[10],[-20]]) 
print(f'Matrix B:\n {B}') 

X = np.dot(pinv_A, B)
print(f'\nDot product:\n{X}') 

C = np.dot(A, X)
print(f'\nChecking:\n{C}') 

Matrix A:
 [[  3  -1   1]
 [  9   3  -3]
 [-12   4  -4]]

PINV:
[[ 0.00980392  0.05555556 -0.03921569]
 [-0.01470588  0.08333333  0.05882353]
 [ 0.01470588 -0.08333333 -0.05882353]]

Matrix B:
 [[  5]
 [ 10]
 [-20]]

Dot product:
[[ 1.38888889]
 [-0.41666667]
 [ 0.41666667]]

Checking:
[[  5.]
 [ 10.]
 [-20.]]


#3

In [ ]:
import numpy as np 
from numpy.linalg import eig

a = np.array([[8, 5, -6],[-12, -9, 12],[-3 , -3, 5]])
print(f'\nthe Eigenvalue/s is/are: ')
print(a)

ev,evt = np.linalg.eig(a)

print(f'\nThe Eigenvalue/s is/are: {ev.round()}')

print(f'\nThe Right Eigenvectors are: \n{evt.round()}\n')


the Eigenvalue/s is/are: 
[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The Eigenvalue/s is/are: [-1.  3.  2.]

The Right Eigenvectors are: 
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]

