<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Linear_Transformation(Demo%202).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Using Python Codes, to find the inverse of a matrix, the matrix is passed to linalg.inv() of the Numpy Module:


In [3]:
import numpy as np 

a = np.array([[4, 3], [-5,9]])
print(a)
inv_a = np.linalg.inv(a)
print(inv_a)

[[ 4  3]
 [-5  9]]
[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [4]:
b = np.array([[20],[26]])
print(b)

[[20]
 [26]]


In [5]:
x = np.linalg.inv(a).dot(b)
print(x)


[[2.]
 [4.]]


In [8]:
x = np.dot(inv_a,b)
print(x)

[[2.]
 [4.]]


#Application


In [33]:
a = np.array([[20, 10], [17, 22]])
print(a)

inv_a1 = np.linalg.inv(a)
print(inv_a)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [23]:
b = np.array([[350], [500]])
print(b)

[[350]
 [500]]


In [34]:
x1 = np.dot(inv_a1, b)
print(x1)

[[10.]
 [15.]]


#ans if correct


In [35]:
c = np.dot(a, x1)
print(c)

[[350.]
 [500.]]


#activity


In [26]:
c = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
print(c)

d = np.array([[25], [-10], [-4]])

x = np.linalg.inv(c).dot(d)
print(x)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 5.]
 [ 3.]
 [-2.]]
