<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Midterm_Exam%2Cipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.


In [1]:
import numpy as np

c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#2


In [26]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6 , 7, 8], [9, 10, 11, 12], [13, 14 , 15, 16]])
print()
print(a)
b = np.triu(a)
print()
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]


#3

In [23]:
import numpy as np 

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

b = np.transpose(a)
print()
print(b)

c = np.matmul(a, b)
print()
print(c)




[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


#4

In [5]:
import numpy as np 

a = np.array([[1, 2, 3], [2, 3, 3], [3, 4, -2]])
print(a)
inv_a = np.linalg.inv(a)
print(inv_a)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#5

In [10]:
import numpy as np 

a = np.array([[1, 2, 3], [2, 3, 3], [3, 4, -2]])
print(a)

det = round(np.linalg.det(a))
print()
print
print(det)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5


#6


In [14]:
import numpy as np

c = np.array([[5, 4, 1], [10, 9, 4], [10, 13, 15]])
inv_c = np.linalg.inv(c)
print(c)
print()
print(inv_c)

d = np.array([[3.4], [8.8], [19.2]])

x = np.dot(inv_c, d)
print("roots =")
print(x)

z = np.dot(c, x) #checking
print("checking =" )
print(z)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]

[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
roots =
[[0.2]
 [0.4]
 [0.8]]
checking =
[[ 3.4]
 [ 8.8]
 [19.2]]
