<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

a = np.array(([1 , 2, 3], [4, 5, 6]))
b = np.array(([1, 2], [3, 4], [5, 6]))
c = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
d = np.array(([1, 2], [3, 4]))
e = np.dot(a,b)

print("a= ")
print(a)
print("b= ")
print(b)
print("c= ")
print(c)
print("d= ")
print(d)

print("AB: ")
print(e)
print("D + D: ")
print(d+d)
print("2C: ")
print(2*c)

a= 
[[1 2 3]
 [4 5 6]]
b= 
[[1 2]
 [3 4]
 [5 6]]
c= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
d= 
[[1 2]
 [3 4]]
AB: 
[[22 28]
 [49 64]]
D + D: 
[[2 4]
 [6 8]]
2C: 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [9]:
import numpy as np

prob2 = np.array([5, 3, -1])

print("Type1 =  ") #since i'm not sure what kind of type to use i added two this one is data type
print(prob2.dtype)
print("Type2 =  ") #
print(type(prob2))
print("Shape =  ")
print(prob2.shape)
print("Dimensions =  ")
print(prob2.ndim)
print("Size = ")
print(prob2.size)


Type1 =  
int64
Type2 =  
<class 'numpy.ndarray'>
Shape =  
(3,)
Dimensions =  
1
Size = 
3
