<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [ ]:
import numpy as np
c = np.zeros((4, 4)) #this where the 4 x 4 matrix
np.fill_diagonal(c, 1) #the fill diagonal method is used to fill a diagonal line with the specific number. it this case the number "1" was used.
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [25]:
import numpy as np
c = np.zeros((4, 4)) #this where the 4 x 4 matrix
np.fill_diagonal(c, 1) #the fill diagonal method is used to fill a diagonal line with the specific number. it this case the number "1" was used.

print("c= ")
print(c)

print("Doubled: ") 
print(2*c)



c= 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Doubled: 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


#Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and

B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [27]:
import numpy as np

A = [2, 7, 4]
B = [3, 9, 8]
C = np.cross(A, B) #where the cross product happens. 

print("A= ")
print(A)
print("B= ")
print(B)
print("C= ")
print(C)

A= 
[2, 7, 4]
B= 
[3, 9, 8]
C= 
[20 -4 -3]
