<a href="https://colab.research.google.com/github/timothyolano/Linear-Algebra-58019/blob/main/Python_Exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and it's operation

In [1]:
import numpy as np

a = np.array(([-5, 0], [4,1]))
b = np.array(([6, -3], [2, 3]))

print("a= ")
print(a)
print("b= ")
print(b)
print("A+B: ")
print(a+b)
print("B-A: ")
print(b-a)
print("A-B: ")
print(a-b)

a= 
[[-5  0]
 [ 4  1]]
b= 
[[ 6 -3]
 [ 2  3]]
A+B: 
[[ 1 -3]
 [ 6  4]]
B-A: 
[[11 -3]
 [-2  2]]
A-B: 
[[-11   3]
 [  2  -2]]
